version: '3.8'

services:
  airbnb_db:
    image: postgres:15
    container_name: airbnb_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: airbnb_clone
    ports:
      - "5434:5432"
    volumes:
      - airbnb_postgres_data:/var/lib/postgresql/data

  airbnb_redis:
    image: redis:7-alpine
    container_name: airbnb_redis
    ports:
      - "6379:6379"

volumes:
  airbnb_postgres_data: